on:
  push:
    branches:
      - github_actions_debug

jobs:
  check:
    name: Check per OS
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    with:
      runs-on_value: ${{ matrix.os }}
      artifacts_version: ${{ github.sha }}
      catboost_package_version: 1.2.5
    uses: ./.github/workflows/check_per_os.yaml
