on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      artifacts_run_id:
        required: false
        type: string
        default: ${{ github.run_id }}
      artifacts_repository:
        required: false
        type: string
        default: ${{ github.repository }}
      catboost_package_name:
        required: false
        type: string
        default: catboost
      is_test_env:
        required: false
        type: boolean
        default: false

jobs:
  publish_widget:
    if: false
    name: Publish catboost-widget on NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Env setup
        shell: pwsh
        run: New-Item -Path built_widget -ItemType Directory

      - name: Download catboost python package visualization widget
        uses: actions/download-artifact@v4
        with:
          name: catboost-python-package-widget-v${{ inputs.version }}
          path: built_widget/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ inputs.artifacts_repository }}
          run-id: ${{ inputs.artifacts_run_id }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          scope: '@andrei_khropov'
      
      - name: Publish catboost-widget npm package
        run: |
          cd ${{ github.workspace }}/built_widget
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish_python_package:
    name: Publish Python package to PyPI
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.is_test_env && 'testpypi' || 'pypi' }}
      url: https://${{ inputs.is_test_env && 'test.pypi.org' || 'pypi.org' }}/p/${{ inputs.catboost_package_name }}

    permissions:
      id-token: write

    steps:
      - name: Download python package dists
        uses: actions/download-artifact@v4
        with:
          pattern: catboost-python-package-dist-*
          path: dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ inputs.artifacts_repository }}
          run-id: ${{ inputs.artifacts_run_id }}

      - if: ${{ ! inputs.is_test_env }}
        name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - if: ${{ inputs.is_test_env }}
        name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/