on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
      catboost_package_name:
        required: false
        type: string
        default: catboost

jobs:
  publish:
    name: Publish
    with:
      version: ${{ inputs.version }}
      catboost_package_name: ${{ inputs.catboost_package_name }}
      artifacts_run_id: 10658718630
    uses: ./.github/workflows/release_publish.yaml
